Symfony\Bundle\LogReaderBundle\Document\File:
    fields:
        id:
            id: true
        name:
            type: string
        path:
            type: string
        lines:
            type: int

    repositoryClass: Symfony\Bundle\LogReaderBundle\Repository\FileRepository