log_reader_web_homepage:
    pattern:  /logreader
    defaults: { _controller: LogReaderBundle:IndexPage:index }

log_reader_web_sort:
    pattern: /logreader/{id}
    defaults: { _controller: LogReaderBundle:IndexPage:sort }

