parameters:
    logreader.controller.indexpage.class: LogReader\LogReaderBundle\Controller\IndexPageController
    logreader.reader.filereader.class: LogReader\LogReaderBundle\Reader\FileReader
services:
    logreader.indexpage.controller:
        class: "%logreader.controller.indexpage.class%"
    logreader.reader.filereader:
        class: "%logreader.reader.filereader.class%"
        arguments: [@doctrine_mongodb.odm.document_manager]
