parameters:
    logreader.controller.indexpage.class: Symfony\Bundle\LogReaderBundle\Controller\IndexPageController
    logreader.reader.filereader.class: Symfony\Bundle\LogReaderBundle\Reader\FileReader
services:
    logreader.indexpage.controller:
        class: "%logreader.controller.indexpage.class%"
    logreader.reader.filereader:
        class: "%logreader.reader.filereader.class%"
        arguments: [@doctrine_mongodb.odm.document_manager]
